DIGITS = [f"{i:03}" for i in range(1, 101)]
SEEDS = ('042', '069', '151', '401', '404', '666', '999', '123', '303', '007')
NOISE = ("0.010", "0.020", "0.030", "0.040")
from glob import glob
import os
from pathlib import Path
import re

include: "rules/ACDC.smk"
include: "rules/simulation.smk"
include: "rules/subject.smk"
include: "rules/rev.smk"
include: "rules/figures.smk"
include: "rules/ml.smk"

subject_data = glob("data/subject_data/*/*[!mask].nii.gz")

FOLDER = [os.path.basename(Path(x).parent) for x in subject_data]

wildcard_constraints:
    seed= '|'.join([re.escape(x) for x in SEEDS]),
    folder= '|'.join([re.escape(x) for x in FOLDER]),
    noise= '|'.join([re.escape(x) for x in NOISE])

rule all:
    input:
        expand("figures/fig{num}.svg", num=[2, 3, 4, 5]),
        expand("figures/supp_fig{num}.svg", num=[1, 2]),
        "figures/supp_tab2.tsv",
        "figures/supp_fig5.svg"

rule combine_tables:
    input:
        "analysis/features_normalized/mrxcat_simulation/features.csv",
        "analysis/tables/mrxcat_simulation/ranks.csv",
        expand("analysis/features_normalized/ACDC/patient{digits}.csv", digits = DIGITS),
        expand("analysis/tables/ACDC/ranks_patient{digits}.csv", digits = DIGITS),
        expand("analysis/features_normalized/subject/{folder}.csv", folder = FOLDER),
        expand("analysis/tables/subject/ranks_{folder}.csv", folder = FOLDER)
    output:
        "analysis/combined/features.tsv",
        "analysis/combined/ranks.tsv"
    conda:
        "tidyverse.yaml"
    script:
        "../code/combine_features.R"

rule SuppTable1:
    input:
        "analysis/calculated_mae/mrxcat_simulation/mae.csv",
        expand("analysis/calculated_mae/ACDC/mae_patient{digits}.csv", digits = DIGITS),
        expand("analysis/calculated_mae/subject/mae_{folder}.csv", folder = FOLDER)
    output:
        "figures/supp_tab1.tsv"
    conda:
        "tidyverse.yaml"
    script:
        "../code/supp_tab1.R"
