valid_slices = {"Proband X1": [8],
                      "Proband X2": [8], 
                      "Proband X4": [8],
                      "Proband X5": [8],
                      "Proband X6": [8],
                      "Proband X7": [8],
                      "Proband X8": [8],
                      "Proband X9": [9],
                      "Proband X10": [8],
                      "Proband X11": [8],
                      "Proband X12": [8],
                      "Proband X13": [9],
                      "Proband X14": [11],
                      "Proband X15": [7]}
